### ISSUE TITLE
Diagrama de sequência

### ISSUE THREAD

**Issue by vaglucas** [lucaspolakti/projeto-hemoesc#5]

**Comment by lucaspolakti** [comment]
![Diagrama de sequência](https://github.com/lucaspolakti/projeto-hemoesc/assets/163211262/5c0ceeeb-2239-401c-a024-32e88adbe611)
[Diagrama de sequência.pdf](https://github.com/lucaspolakti/projeto-hemoesc/files/14939520/Diagrama.de.sequencia.pdf)
